Added contributing guide lines
KnpLabs/bad-jokes pull request #41
Opened 2021-10-20 05:34 UTC by eveyonline

2021-10-20 06:21 UTC, qroques approved these changes

2021-10-20 06:23 UTC, NicolasNSSM approved these changes
This PR clearly will make the futur of this project cleaner and greater, thank you!

2022-10-21 12:21 UTC, merged

2022-10-21 12:26 UTC, qroques requested changes

2022-10-21 12:26 UTC, qroques commented on CONTRIBUTING.md
> +#### Before submitting a bug
It seems it has a jump of title level 

```suggestion
### Before submitting a bug

```

2022-10-21 12:26 UTC, qroques commented on CONTRIBUTING.md
> +#### How to submit a (good) bug report
```suggestion
### How to submit a (good) bug report

```

2022-10-21 12:26 UTC, qroques commented on CONTRIBUTING.md
> +```
```suggestion
```shell
```

2022-10-21 12:26 UTC, qroques commented on CONTRIBUTING.md
> +```
```suggestion
```shell
```

2022-10-21 12:26 UTC, qroques commented on CONTRIBUTING.md
> +```
```suggestion
```shell
```

2022-10-21 12:26 UTC, qroques commented on CONTRIBUTING.md
> +```
```suggestion
```shell
```

2022-10-21 12:30 UTC, qroques commented
:ah: